### ISSUE TITLE
Implement rTorrentProvider

### ISSUE THREAD

**Issue by vinz243** [vinz243/pTorrent#3]
https://github.com/roastlechon/nodejs-rtorrent/blob/master/src/node/lib/rtorrent.js
https://code.google.com/p/gi-torrent/wiki/rTorrent_XMLRPC_reference

**Comment by nVitius** [comment]
@vinz243: are you still looking to work on this more? I've been thinking about doing something similar and would like to help out.

**Comment by HDVinnie** [comment]
would be nice to see this active again....looks good but fails on install.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart pTorrent@0.0.2
6 info start pTorrent@0.0.2
7 verbose unsafe-perm in lifecycle true
8 info pTorrent@0.0.2 Failed to exec start script
9 verbose stack Error: pTorrent@0.0.2 start: `node server.js --env=dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid pTorrent@0.0.2
11 verbose cwd /Users/Vinnie/Downloads/pTorrent-master
12 error Darwin 14.5.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.3
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error pTorrent@0.0.2 start: `node server.js --env=dev`
17 error Exit status 1
18 error Failed at the pTorrent@0.0.2 start script 'node server.js --env=dev'.
18 error This is most likely a problem with the pTorrent package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js --env=dev
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs pTorrent
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls pTorrent
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by vinz243** [comment]
It starts fine for me with node version v6.2.1 on Ubuntu 16.04. What is your node version?  EDIT: maybe try to update to latest node using creationix/nvm ?

@nVitius sorry for delay, I currently put this on hold for lack of real interest. I might take it back next year but not sure. If you want to work on it feel free to fork it ;)

**Comment by vinz243** [comment]
btw @HDVinnie this would deserve its own issue
