### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by HDVinnie** [vinz243/pTorrent#7]
would be nice to see this active again....looks good but fails on install.

```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart pTorrent@0.0.2
6 info start pTorrent@0.0.2
7 verbose unsafe-perm in lifecycle true
8 info pTorrent@0.0.2 Failed to exec start script
9 verbose stack Error: pTorrent@0.0.2 start: `node server.js --env=dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid pTorrent@0.0.2
11 verbose cwd /Users/Vinnie/Downloads/pTorrent-master
12 error Darwin 14.5.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.3
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error pTorrent@0.0.2 start: `node server.js --env=dev`
17 error Exit status 1
18 error Failed at the pTorrent@0.0.2 start script 'node server.js --env=dev'.
18 error This is most likely a problem with the pTorrent package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js --env=dev
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs pTorrent
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls pTorrent
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

Currently running OS X Yosemite version 10.10.5 (14F27)
Node.js v6.2.1 and npm v3.9.3

**Comment by HDVinnie** [comment]
going to try on Ubuntu 16.04 LTS and will report back

**Comment by vinz243** [comment]
Don't forget to use lastest version using nvm

**Comment by HDVinnie** [comment]
im not sure what the issue is.....i do css, sass, less....styling for a living.

```
 hdvinnie@ubuntu]:(8.7kb)~$ cd '/home/hdvinnie/Downloads/pTorrent-master' 
[hdvinnie@ubuntu]:(10.3kb)~/Downloads/pTorrent-master$ npm start

> pTorrent@0.0.2 start /home/hdvinnie/Downloads/pTorrent-master
> node server.js --env=dev

module.js:442
    throw err;
    ^

Error: Cannot find module 'core-js/fn/object/assign'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/hdvinnie/Downloads/pTorrent-master/server.js:2:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! pTorrent@0.0.2 start: `node server.js --env=dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pTorrent@0.0.2 start script 'node server.js --env=dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pTorrent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js --env=dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pTorrent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pTorrent
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hdvinnie/Downloads/pTorrent-master/npm-debug.log

```

**Comment by HDVinnie** [comment]
sorry to bother you....i know you have not worked on this in some time but if i can get it loaded I would like to check it out and possibly work on it.

**Comment by vinz243** [comment]
Hmm I think I already got this issue, which is strange since I retried installing it on a clean new Ubuntu and it was working like a charm. Maybe try `npm i core-js` ?

**Comment by vinz243** [comment]
No problem it's nice to see this project hasn't fallen to oblivion yet :)

**Comment by HDVinnie** [comment]
[hdvinnie@ubuntu](%287.7kb%29~/Downloads/pTorrent-master$):(10.3kb)~/Downloads/pTorrent-master$ npm i core-js
pTorrent@0.0.2 /home/hdvinnie/Downloads/pTorrent-master
└── core-js@2.4.0 

npm WARN pTorrent@0.0.2 No repository field.
npm WARN pTorrent@0.0.2 No license field.

This is a clean install of Ubuntu

**Comment by vinz243** [comment]
Try running :

``` bash
$ cd pTorrent # if you haven't done it already 
$ npm install
$ npm start
```

**Comment by HDVinnie** [comment]
Worked now....im going to post this for reference to some warnings and depreciated values. Im guessing this has no functionality yet right?

```
[hdvinnie@ubuntu]:(7.7kb)~/Downloads/pTorrent-master$ npm install
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
fetchMetadata → addNameRa ▄ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
loadDep:lodash._root      ▄ ╢████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░fetchMetadata → network   ▀ ╢████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> node-sass@3.7.0 install /home/hdvinnie/Downloads/pTorrent-master/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/hdvinnie/Downloads/pTorrent-master/node_modules/node-sass/vendor/linux-x64-48/binding.node

> phantomjs@2.1.7 install /home/hdvinnie/Downloads/pTorrent-master/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [======================================--] 95%
Received 22866K total.
Extracting tar contents (via spawned process)
Removing /home/hdvinnie/Downloads/pTorrent-master/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1465929751078/phantomjs-2.1.1-linux-x86_64 -> /home/hdvinnie/Downloads/pTorrent-master/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/hdvinnie/Downloads/pTorrent-master/node_modules/phantomjs/lib/phantom/bin/phantomjs

> node-sass@3.7.0 postinstall /home/hdvinnie/Downloads/pTorrent-master/node_modules/node-sass
> node scripts/build.js

"/home/hdvinnie/Downloads/pTorrent-master/node_modules/node-sass/vendor/linux-x64-48/binding.node" exists. 
 testing binary.
Binary is fine; exiting.

> pTorrent@0.0.2 install /home/hdvinnie/Downloads/pTorrent-master
> browserify -s WebTorrent -e node_modules/webtorrent/ > node_modules/webtorrent/webtorrent.debug.js

pTorrent@0.0.2 /home/hdvinnie/Downloads/pTorrent-master
├─┬ babel-core@6.9.1 ...
  └── xmlbuilder@2.6.5 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN url-loader@0.5.7 requires a peer of file-loader@* but none was installed.
npm WARN pTorrent@0.0.2 No repository field.
npm WARN pTorrent@0.0.2 No license field.
[hdvinnie@ubuntu]:(7.7kb)~/Downloads/pTorrent-master$ npm start

> pTorrent@0.0.2 start /home/hdvinnie/Downloads/pTorrent-master
> node server.js --env=dev

Listening at 127.0.0.1:8080
Opening your system browser...
webpack: wait until bundle finished: /assets/app.js
Hash: 36012391000e9fa5cb3a
Version: webpack 1.13.1
Time: 180803ms
 Asset     Size  Chunks             Chunk Names
app.js  2.96 MB       0  [emitted]  main
chunk    {0} app.js (main) 2.62 MB [rendered]
    [0] multi main 52 bytes {0} [built]
    [1] (webpack)-dev-server/client?http://46.101.88.132:8080/ 2.67 kB {0} [built]
    ...
  [757] ./~/xmlrpc/lib/server.js 2.59 kB {0} [built]

WARNING in ./src/components/Main.js

/home/hdvinnie/Downloads/pTorrent-master/src/components/Main.js
  20:8  warning  "SocketClient" is defined but never used  no-unused-vars
  22:8  warning  "Debug" is defined but never used         no-unused-vars

✖ 2 problems (0 errors, 2 warnings)


WARNING in ./src/stores/TorrentStore.js

/home/hdvinnie/Downloads/pTorrent-master/src/stores/TorrentStore.js
   7:1  warning  Unexpected console statement  no-console
  30:3  warning  Unexpected console statement  no-console
  40:4  warning  Unexpected console statement  no-console

✖ 3 problems (0 errors, 3 warnings)


WARNING in ./src/adapters/SockAdapter/SocketClient.js

/home/hdvinnie/Downloads/pTorrent-master/src/adapters/SockAdapter/SocketClient.js
  37:34  warning  "reject" is defined but never used               no-unused-vars
  56:7   warning  "ProxiedSocketClient" is defined but never used  no-unused-vars
  64:11  warning  Unexpected console statement                     no-console

✖ 3 problems (0 errors, 3 warnings)


WARNING in ./src/components/TorrentComponent.js

/home/hdvinnie/Downloads/pTorrent-master/src/components/TorrentComponent.js
  22:5   warning  Unexpected console statement  no-console
  34:31  warning  Trailing spaces not allowed   no-trailing-spaces

✖ 2 problems (0 errors, 2 warnings)


WARNING in ./src/adapters/SockAdapter/index.js

/home/hdvinnie/Downloads/pTorrent-master/src/adapters/SockAdapter/index.js
   7:17  warning  Trailing spaces not allowed  no-trailing-spaces
  12:15  warning  Unexpected trailing comma    comma-dangle

✖ 2 problems (0 errors, 2 warnings)


WARNING in ./src/adapters/SockAdapter/Torrent.js

/home/hdvinnie/Downloads/pTorrent-master/src/adapters/SockAdapter/Torrent.js
   42:27  warning  Trailing spaces not allowed         no-trailing-spaces
  145:7   warning  "self" is defined but never used    no-unused-vars
  164:32  warning  "reject" is defined but never used  no-unused-vars

✖ 3 problems (0 errors, 3 warnings)


WARNING in ./src/adapters/SockAdapter/Client.js

/home/hdvinnie/Downloads/pTorrent-master/src/adapters/SockAdapter/Client.js
   2:8  warning  "SocketClient" is defined but never used  no-unused-vars
  17:4  warning  Unexpected console statement              no-console

✖ 2 problems (0 errors, 2 warnings)

webpack: bundle is now VALID.
```

**Comment by vinz243** [comment]
For now basic torrent downloading has been done, only you need to add to the queue via code - and only for magnets - and it also report progress to the UK accordingly.

**Comment by vinz243** [comment]
*meant UI not UK

**Comment by jacksonstauffer** [comment]
Hey, your conversation is sending everyone emails. Why don't you two get a
room?
https://finit.co/chat/ptorrent

**Comment by HDVinnie** [comment]
how about you unsubscribed to this thread.

**Comment by uplusion23** [comment]
@vinz243 Ever thought about continuing this? It looks amazing, and well needed by the community. I'm surprised it never took off.

**Comment by vinz243** [comment]
@uplusion23 maybe one day I'll continue this. But the code is a mess and hard to maintain. Also, the problem is that it looks good but with many torrent it's just a mess.
